<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'The position from left to right in the header. eg. 1' => 'De positie van links naar rechts in de topbar. bv. 1',
    'Are you sure you want to delete this item' => 'Ben je zeker dat je dit wilt verwijderen',
    'Are you sure?' => 'Ben je zeker',
    'Close' => 'Sluiten',
    'Create' => 'Nieuw',
    'Create Quicklink success' => 'Nieuwe quicklink aangemaakt',
    'Create more' => 'Nieuwe aanmaken',
    'Create new Quicklink' => 'Nieuwe quicklink',
    'Create new Quicklinks' => 'Nieuwe quicklinks',
    'Delete all' => 'Verwijder alle',
    'ID' => 'id',
    'Icon' => 'Icoon',
    'In new window?' => 'In nieuw venster?',
    'Link' => 'Link',
    'No' => 'Nee',
    'Position' => 'Positie',
    'Quicklinks' => 'Quicklinks',
    'Save' => 'Opslaan',
    'Title' => 'Titel',
    'Update' => 'Bewerk',
    'Update Quicklink' => 'Bewerk quicklink',
    'User' => 'Gebruiker',
    'Yes' => 'Ja',
];
